apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: 471112694187.dkr.ecr.us-west-2.amazonaws.com/my-sample-app/my-sample-app:
        env:
        - name: ENVIRONMENT
          value: "prod"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: prod
spec:
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
