apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
- ../base
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: sample-app
  spec:
    replicas: 2
    template:
      spec:
        containers:
        - name: sample-app
          env:
          - name: ENVIRONMENT
            value: "prod"
